
mybatis-plus:
  mapper-locations: classpath:com/beneway/common/**/mapper/*.xml,classpath:com/beneway/common/mapper/**/*.xml
  type-aliases-package: com.beneway.**.entity
  type-enums-package: com.beneway.**.enums
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_UUID
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL语句

sa-token:
  token-name: access_token
  # token风格
  token-style: uuid

# 自定义配置
customize:
  logPath: logs
  filePath: files/
  file:
    filePath: files/

